export default {
    DESIGNER: {
        NEW_TEMPLATE: '새 템플릿',
        HASNOT_DEFINED_PAGE_SIZE: '정의된 판형정보가 없습니다.',
        NOT_LOGGED_IN: '로그인되지 않았습니다.',
        MAKE: '만들기',
        PAGE_SIZE: '판형',
        PAGE_SIZE_DETAIL_INFO: '판형 상세정보',
        PAPER_TYPE: '용지구분',
        LINESPACING_SIZE: '배수',
        COLUMN: '단',
        COLUMN_INSIDE_MARGIN: '단안쪽여백',
        COLUMN_OUTSIDE_MARGIN: '단바깥쪽여백',
        COLUMN_COUNT: '단수',
        COLUMN_SIZE: '단너비',
        COLUMN_SPACING: '단간격',
        COLUMN_OTHER: '보정값',
        COLUMN_TOTAL_SIZE: '단전체너비',
        COLUMN_INFO: '너비정보',
        LINE: '행',
        LINE_TOP_MARGIN: '행위쪽여백',
        LINE_BOTTOM_MARGIN: '행아래쪽여백',
        LINE_HEIGHT: '행높이',
        LINE_COUNT: '행수',
        LINE_SPACING: '행간격',
        LINE_OTHER: '보정값',
        LINE_TOTAL_SIZE: '행전체높이',
        LINE_INFO: '높이정보',
    },
    MENUITEM: {
        DESIGNER_NEW: '새 템플릿',
        DESIGNER_OPEN: '불러오기',
        DESIGNER_SAVE: '저장하기',
        DESIGNER_SAVEAS: '새이름으로 저장',
        DESIGNER_LOGOUT: '로그아웃',
    },
    TOOLBAR: {
        TEXT_SIZE: '크기',
        TEXT_XSCALE: '장평',
        TEXT_LETTERSPACING: '자간',
        TEXT_LINEHEIGHT: '행간',
        TEXT_INDENT: '들여쓰기',
        TEXT_UNDERLINE: '밑줄',
        TEXT_STRIKELINE: '취소선',
        TEXT_ALIGN_LEFT: '좌측정렬',
        TEXT_ALIGN_CENTER: '가운데정렬',
        TEXT_ALIGN_RIGHT: '우측정렬',
        TEXT_ALIGN_JUSTIFY: '좌우정렬',
        TEXT_VALIGN_TOP: '위쪽정렬',
        TEXT_VALIGN_MIDDLE: '중간정렬',
        TEXT_VALIGN_BOTTOM: '아랫쪽정렬',
        TEXT_VALIGN_JUSTIFY: '위아래정렬',

        PAGEOBJECT_DRAW_SELECT: '선택(S)',
        PAGEOBJECT_DRAW_FRAME_EDITMODE: '프레임 수정모드(E)',
        PAGEOBJECT_DRAW_FRAME_MOVEMODE: '프레임 이동모드(Q)',
        PAGEOBJECT_DRAW_TEXTMODE: '텍스트모드(W)',
        PAGEOBJECT_DRAW_EMPTYFRAME: '빈프레임(B)',
        PAGEOBJECT_DRAW_TITLEFRAME: '제목프레임(T)',
        PAGEOBJECT_DRAW_TEXTFRAME: '텍스트프레임(X)',
        PAGEOBJECT_DRAW_IMAGEFRAME: '이미지프레임(I)',
        PAGEOBJECT_DRAW_LINE: '선(L)',

        PAGEOBJECT_CONTROL_FLIP_TO_BACK: '프레임 뒤로 보내기',
        PAGEOBJECT_CONTROL_FLIP_TO_FRONT: '프레임 앞으로 보내기',
        PAGEOBJECT_CONTROL_ALIGN_CENTER: '프레임 가운데 정렬',
        PAGEOBJECT_CONTROL_ALIGN_LEFT: '프레임 왼쪽 정렬',
        PAGEOBJECT_CONTROL_ALIGN_RIGHT: '프레임 오른쪽 정렬',
        PAGEOBJECT_CONTROL_VALIGN_MIDDLE: '프레임 중간 정렬',
        PAGEOBJECT_CONTROL_VALIGN_TOP: '프레임 위쪽 정렬',
        PAGEOBJECT_CONTROL_VALIGN_BOTTOM: '프레임 아랫쪽 정렬',
        PAGEOBJECT_CONTROL_MOVE_UP: '프레임 위로 단위이동',
        PAGEOBJECT_CONTROL_MOVE_DOWM: '프레임 아래로 단위이동',
        PAGEOBJECT_CONTROL_MOVE_LEFT: '프레임 왼쪽으로 단위이동',
        PAGEOBJECT_CONTROL_MOVE_RIGHT: '프레임 오른쪽으로 단위이동',
        PAGEOBJECT_CONTROL_MOVE_LEFTUP: '프레임 좌측위로 단위이동',
        PAGEOBJECT_CONTROL_MOVE_RIGHTUP: '프레임 우측위로 단위이동',
        PAGEOBJECT_CONTROL_MOVE_LEFTDOWN: '프레임 좌측아래로 단위이동',
        PAGEOBJECT_CONTROL_MOVE_RIGHTDOWN: '프레임 우측아래로 단위이동',
        PAGEOBJECT_CONTROL_MOVE_STEP: '이동간격',
        PAGEOBJECT_CONTROL_ROTATE_LEFT: '프레임 좌측으로 단위회전',
        PAGEOBJECT_CONTROL_ROTATE_RIGHT: '프레임 우측으로 단위회전',
        PAGEOBJECT_CONTROL_ROTATE_STEP: '회전간격',
        PAGEOBJECT_CONTROL_REMOVE: '프레임 삭제',

        PAGEOBJECT_TRANSFORM_WIDTH: '너비',
        PAGEOBJECT_TRANSFORM_HEIGHT: '높이',
        PAGEOBJECT_TRANSFORM_PADDING_LEFT: '왼쪽여백',
        PAGEOBJECT_TRANSFORM_PADDING_RIGHT: '오른쪽여백',
        PAGEOBJECT_TRANSFORM_PADDING_TOP: '윗쪽여백',
        PAGEOBJECT_TRANSFORM_PADDING_BOTTOM: '아래쪽여백',
        PAGEOBJECT_TRANSFORM_BORDER_LEFT: '왼쪽테두리',
        PAGEOBJECT_TRANSFORM_BORDER_RIGHT: '오른쪽테두리',
        PAGEOBJECT_TRANSFORM_BORDER_TOP: '윗쪽테두리',
        PAGEOBJECT_TRANSFORM_BORDER_BOTTOM: '아래쪽테두리',
        PAGEOBJECT_TRANSFORM_BORDER_COLOR: '테두리색상',
        PAGEOBJECT_TRANSFORM_BORDER_STYLE: '테두리스타일',
        PAGEOBJECT_TRANSFORM_OVERLAP_METHOD_OVERLAP: '겹치기',
        PAGEOBJECT_TRANSFORM_OVERLAP_METHOD_FRAMEBOX: '프레임박스',
        PAGEOBJECT_TRANSFORM_OVERLAP_METHOD_SHAPE: '테두리',
        PAGEOBJECT_TRANSFORM_OVERLAP_METHOD_JUMP: '줄넘기',

        DOCUMENTSTATUS_SCALE: '비율',
    },
    UI: {
        ALERT: '알림',
        CANCEL: '취소',
        CLOSE: '닫기',
        CONFIRM: '확인',
        NO: '아니요',
        OK: '확인',
        OPEN: '열기',
        YES: '예',
    }
};